### ISSUE TITLE
Anti-Cobblestone recipe bugged

### ISSUE THREAD

**Issue by josiahkeeler** [Theguyhere0/compressed-cobblestone#3]
Bug: Crafting 9 T10 cobblestone produces 1 T10 cobblestone. Uncrafting Anti-Cobblestone works as expected.
Expected behavior: 9 T10 Cobblestone should produce 1 Anti-Cobblestone

![2020-08-14_09 57 45](https://user-images.githubusercontent.com/29555490/90274269-21bdfc80-de15-11ea-8f6c-0a2ba5d7a509.png)
![2020-08-14_09 57 35](https://user-images.githubusercontent.com/29555490/90274274-22569300-de15-11ea-9541-67b5ca08b19d.png)

**Comment by Theguyhere0** [comment]
Looks like I didn't change one part of my code I copy-pasted. Will release a bug fix update soon.

**Comment by Theguyhere0** [comment]
v1.4.1 should fix this bug
